<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2de17701cacab8eeba92e27bc7109e10
{
    public static $prefixLengthsPsr4 = array (
        'J' =>
        array (
            'Jankx\\Extensions\\UserCredits\\' => 29,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jankx\\Extensions\\UserCredits\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2de17701cacab8eeba92e27bc7109e10::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2de17701cacab8eeba92e27bc7109e10::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2de17701cacab8eeba92e27bc7109e10::$classMap;

        }, null, ClassLoader::class);
    }
}
